---
# Ansible Galaxy Collections Requirements
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  - name: community.general
  - name: community.docker
  - name: ansible.posix
