---
# Main Ansible Playbook for Standard Notes IaC Deployment
# See docs/ARCHITECTURE.md for deployment flow and role responsibilities

- name: Deploy Standard Notes with security hardening
  hosts: standardnotes
  become: true
  gather_facts: true

  roles:
    - role: common
      tags: [common, system]

    - role: users
      tags: [users, security]

    - role: ssh-hardening
      tags: [ssh, security]

    - role: firewall
      tags: [firewall, security]

    - role: fail2ban
      tags: [fail2ban, security, ids]

    - role: docker_engine
      tags: [docker, infrastructure]

    - role: app_service
      tags: [app, standardnotes]

    - role: backup_restore
      tags: [backup, operations]

    - role: motd
      tags: [motd, ux]

  post_tasks:
    - name: Check if reboot is required (first run only)
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Schedule reboot if required
      ansible.builtin.debug:
        msg: "Reboot required after first deployment. Will reboot in 1 minute."
      when: reboot_required.stat.exists

    - name: Reboot server if required
      ansible.builtin.reboot:
        msg: "Rebooting after initial hardening (SSH, firewall, kernel params)"
        pre_reboot_delay: 60
        post_reboot_delay: 30
        reboot_timeout: 600
      when: reboot_required.stat.exists
